# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a6de90a13164a1982261c0e0acd59288"
name = "walmart-mcs-shop-v1"
application_url = "https://mcs-shopify.vercel.app/"
embedded = true
handle = "walmart-mcs-shop-v1"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mcs-shopify.vercel.app/auth/callback",
  "https://mcs-shopify.vercel.app/auth/shopify/callback", 
  "https://mcs-shopify.vercel.app/api/auth/callback",
  "https://mcs-shopify.vercel.app/api/auth"
]

[pos]
embedded = false
